Topic/integration
jrl-umi3218/RBDyn pull request #66
Opened 2019-07-09 04:48 UTC by aescande

This PR reworks the numerical integration for the non-trivial joints (planar, spherical and free):
* fix a sign error in the Magnus expansion and conditionally extend the expansion to 5 terms, depending on a user-defined precision,
* properly take into account that translation velocities are expressed in the successor frames (FS) by integrating the motion of this frame instead of considering it constant over the integration step,
* the error done during the integration is estimated and used to subdivide the integration step if necessary. Consequently, integration can be carried out on large intervals (tested up to 1 second),
* new tests are added, old ones are reworked
* [WIP] detailed mathematical notes are added to the documentation

This PR is not polished yet, but I'd like to have some general feedback first/while polishing.
First of all the tests. I'm currently performing 4 types:
 * comparing integration at constant velocity with analytical formula (for constant velocity it is possible to derive these formula, which is not the case for constant acceleration)
 * comparing the integration at constant acceleration with step dt to N integrations at constant velocity with step dt/N, changing the velocity between those integrations. N is a large number (10000 right now)
 * checking the self-consistency of the integration: one integration with step dt should yield the same result as N integrations with step dt/N. 
 * checking the consistency of the integration with the jacobian matrix in the following way: I take a point P on the body after the joint. Taking a constant velocity v for the joint, we should get the same result by
(i) integrating the joint position and computing the new position of P
(ii) integrating Jv, where J is the Jacobian matrix of the point.

The last test is an attempt to ensure that the integration is coherent with the library as a whole, because it could be possible to misunderstand the conventions adopted in RBDyn and write a wrong integration that could however pass the 3 first tests. The idea of using the Jacobian matrix is to get quantities in the world frame, where there is no specific convention, from whatever the original spaces are for the joint variables and velocities/accelerations. If anyone has a better idea, I'd be happy to hear it.
Something related is done in `EulerTestV2` in `AlgoTest`, but quantites are brought back in some variable space, which makes the test dependent on conventions, and makes it actually wrong for planar and free joints (although because of the very low accuracy required, the planar test is still passing - but I had to disable the one for free joint). I believe this test should be removed completely.

Another point is that the estimation of the error is adding some overhead. I didn't measure it for now, as it is up to a few dozens of scalar additions/multiplications, but it could be equivalent to the integration computation in itself. Does it seems ok? Or do I add a flag/versions without any precision check?

Things still to do:
* Change name from `eulerIntegration` to `integration` or `numericIntegration` to better reflect what's happening in the functions. Keep old names around but marked as deprecated. Can we change the name of the file?
* Clean up remaining commented code and debug outputs
* Finish to write and integrate mathematical documentation

The PR solves #35, without addressing #65 (I could not get an integration coherent with the Jacobian matrix when changing the convention for the planar joint, and I don't get where I'm making a mistake).

2019-07-10 00:58 UTC, aescande commented
@gergondet : there does not seems to be a mechanism for deprecation in RBDyn yet. Do you have any guidelines on how to proceed?
Here are a few options I see:
* using `[[deprecated]]` (requires c++14)
* using some CMake facilities: https://stackoverflow.com/a/41225414/11611648
* writing some macro by hand (where?) as in https://stackoverflow.com/a/295229/11611648

2019-07-11 10:11 UTC, aescande commented
Baring feedbacks, I'm done with the code so far.
Code review can start :)

2019-08-14 05:50 UTC, vsamy reviewed
The code seems to be clean. There is just some few changes.
Although, you might need to transform your `if (...) ...;` in 
```
if (...)
{
  ...
}
```

2019-08-14 05:50 UTC, vsamy commented on src/NumericalIntegration.cpp
> +std::pair<Vector3d, bool> magnusExpansion(const Vector3d & w, const Vector3d & wD, double step,
I think the return type is not intuitive, the function returns `false` if it worked and `true` if we don't know.
At the 5th step, there is no check whether or not the operation succeed and the return value is always `true` but could also be a `false`.

2019-08-14 05:50 UTC, vsamy commented on src/RBDyn/NumericalIntegration.h
> +                                                      bool breakOnWarning = false);
`breakOnWarning` should be renamed since no warning is emitted (not to the user/developer).

2019-08-14 05:50 UTC, vsamy commented on src/CMakeLists.txt
> +  FK.cpp FV.cpp FA.cpp Jacobian.cpp ID.cpp IK.cpp IS.cpp FD.cpp NumericalIntegration.cpp
I am not really use to deal with deprecation stuff but if `EulerIntegration.cpp` is deleted then the program just won't compile at all for old style and there is no need to mark it deprecated. Should'nt the file stay alive for few release iteration before it is definitively deleted?

2019-08-14 05:50 UTC, vsamy commented on src/NumericalIntegration.cpp
> +std::pair<Quaterniond, bool> SO3Integration(const Quaterniond & qi,
Is c++17 ok? If so, `std::optional` would suit exactly the behavior you want with the pairs.

2019-08-14 05:50 UTC, vsamy commented on src/RBDyn/NumericalIntegration.h
> + */
Add an `@return` statement to explain the function output.

2019-10-31 09:31 UTC, gergondet requested changes
Sorry for the long time it took me to get to it. I don't have much issues with the PR, just small readability/efficiency concerns. I've rebased on the current master so you should make sure that you nuke your local branch before pushing back to it

I might be possible to integrate your latex note in the doxygen. I'll look into it

2019-10-31 09:31 UTC, gergondet commented on src/IS.cpp
> +      nColsWanted = static_cast<long>(jacMomentsAndForces[i].cols());
very minor but it would make more sense to change `nColsWanted` type in the first place

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +                                          double absEps)
I think I'd rather have: (same goes for `SO3Integration`)
```cpp
Eigen::Quaterniond magnusExpansion(const Vector3d & w,
                                    const Vector3d & wD,
                                    double step,
                                    double relEps,
                                    double absEps,
                                    bool & failed)
```

this will make the code more readable and slightly more optimal

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +}
Maybe we want a version that doesn't check bounds and just compute the 5 terms regardless (such as when you use it in `freeJointIntegration_`) but that has to be benchmarked....

In that version when you care about the boolean you are acutally computing O5 for nothing since you throw the result away

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +}
I had a short discussion with @aescande as this implementation didn't strictly match the equation in the note, in conclusion:
- we can change the inside of the loop to be marginally more precise
  - increment `wi` by `halfNthStep * wD` before computing `qe` (resp. change the increment at the end of the loop)
  - changing `qe` to `Quaterniond qe = rbd::SO3Integration(qh, wi, wD, halfNthStep).first;`
- we keep `qf` in the end although it would be technically more correct to compute `qf` from the final `qh`, the reason being precision is good enough and this avoids one SO3Integration in the most common use case (i.e. `n = 1`)

I suggest adding a note to "4.3 Implementation details" of the note to indicate that we take some shortcuts in the implementation since at this point we have made sure that `step` is sufficiently small to have good precision here. A comment here wouldn't hurt as well :-)

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +  auto qf = rbd::SO3Integration(qi, wi, wD, step, prec, prec);
Should also break on failure

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +  double nthStep2 = nthStep * halfNthStep;
Add a comment that this is the same as `nthStep * nThStep / 2`, this got me super confused ^^

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +}
I think this `breakOnWarning` parameter is very confusing (but very useful). I'd rather we have two functions:
- `SO3Integration` always returns the integration result regardless of magnus expansion result (that magnus expansion then doesn't perform as many checks)
- `SO3IntegrationIfGoodStep` (or a better name ^^) that checks the output of magnus expansion (and that magnus expansion doesn't have to bother with the fifth term computation)

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +      Vector3d vD(alphaD[3], alphaD[4], alphaD[5]);
They could all be maps no?

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +      Vector3d wD(alphaD[0], alphaD[1], alphaD[2]);
Could be Map also?

2019-10-31 09:31 UTC, gergondet commented on src/NumericalIntegration.cpp
> +    default:;
```cpp
default:
  break;
```

2019-10-31 09:31 UTC, gergondet commented on src/RBDyn/EulerIntegration.h
> +#endif
Add `RBDYN` in all those macros name if they are going to be included :)

2019-10-31 09:31 UTC, gergondet commented on src/RBDyn/EulerIntegration.h
> +PRAGMA_WARNING(EulerIntegration.h is a deprecated header.Please consider using NumericalIntegration.h instead.)
-Please consider using
+Use

2019-10-31 09:31 UTC, gergondet commented on src/RBDyn/EulerIntegration.h
> +                                            double prec = 1e-10)
Don't add the `prec` argument (applies to `eulerIntegration` and `sEulerIntegration` as well)

2019-10-31 09:31 UTC, gergondet commented on src/RBDyn/NumericalIntegration.h
> +#include <rbdyn/deprecated.hh>
I don't think this is needed here

2022-07-13 14:45 UTC, gergondet approved these changes

2022-07-13 18:15 UTC, merged